version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: increase
    groups:
      bundler:
        dependency-type: "production"
    schedule:
      interval: "daily"
